CommissionsApplication.WebUI/Models/Concrete/UserViewModel.cs
namespace CommissionsApplication.WebUI.Models.Concrete
{
    public class UserViewModel
    {
        public int UserId { get; set; }

        public string Name { get; set; }

        public string Login { get; set; }

        public string Email { get; set; }

        public string UserRole { get; set; }
    }
}

CommissionsApplication.WebUI/Controllers/GlobalController.cs
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using CommissionsApplication.WebUI.App_GlobalResources;
using CommissionsApplication.WebUI.Infrastructure.Filters;

namespace CommissionsApplication.WebUI.Controllers
{
    public class GlobalController : Controller
    {
        [AjaxOnly]
        public ActionResult Locales()
        {
            var locales = typeof (Global).GetProperties(BindingFlags.Public | BindingFlags.Static)
                .Where(prop => prop.PropertyType == typeof (string))
                .ToDictionary(prop => prop.Name, prop => (string) prop.GetValue(null, null));

            return Json(new
            {
                locales
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

CommissionsApplication.WebUI/Controllers/UsersController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using CommissionsApplication.DAL.Helpers.Filters;
using CommissionsApplication.DAL.Helpers.Infrastructure.Exceptions;
using CommissionsApplication.DAL.Repositories.Abstract;
using CommissionsApplication.Domain.Entities;
using CommissionsApplication.WebUI.App_GlobalResources;
using CommissionsApplication.WebUI.Infrastructure.Attributes;
using CommissionsApplication.WebUI.Infrastructure.Filters;
using CommissionsApplication.WebUI.Infrastructure.Mapping.Abstract;
using CommissionsApplication.WebUI.Models.Concrete;

namespace CommissionsApplication.WebUI.Controllers
{
    [AjaxAuthorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;

        public UsersController(IMapper mapper, IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            return View();
        }

        [AjaxOnly]
        public ActionResult Users(string orderBy = null, [JsonBinder] UserFilter filter = null)
        {
            var userModels = _unitOfWork.UserRepository.GetAll(orderBy, filter)
                .Select(u => _mapper.UserViewModelMapper.Map(u))
                .ToList();

            return Json(new
            {
                totalItems = userModels.Count,
                items = userModels
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [AjaxOnly]
        public ActionResult UserEdit(int id)
        {
            var user = _unitOfWork.UserRepository.GetByKey(id);
            if (user == null)
                return PartialView("ModalError", new ErrorModel {Message = Global.Error_UserRemoved});

            var userModel = _mapper.UserEditModelMapper.Map(user);

            ViewBag.Title = Global.UserEdit_Title;

            return PartialView(userModel);
        }

        [HttpPost]
        [AjaxOnly]
        [ValidateAntiForgeryToken]
        public ActionResult UserEdit(UserEditModel userModel)
        {
            if (!ModelState.IsValid)
                return PartialView("ModalError", new ErrorModel {Message = Global.Error_UserValidation});
            if (!_unitOfWork.UserRepository.Exists(userModel.UserId))
                return PartialView("ModalError", new ErrorModel {Message = Global.Error_UserRemoved});

            var user = _mapper.UserMapper.Map(userModel);
            if (string.IsNullOrWhiteSpace(userModel.Password))
            {
                user.Password = _unitOfWork.UserRepository.GetPasswordByKey(userModel.UserId);
            }
            try
            {
                _unitOfWork.UserRepository.Update(user);
                _unitOfWork.Commit();

                return Json(new
                {
                    id = user.UserId
                });
            }
            catch (RepositoryConcurrencyException)
            {
                return PartialView("ModalError", new ErrorModel {Message = Global.Error_UserConcurrency});
            }
            catch (RepositoryDuplicateException)
            {
                //TODO: Not user friendly
                return PartialView("ModalError", new ErrorModel { Message = Global.Error_UserValidation });
            }
        }

        [HttpGet]
        [AjaxOnly]
        public ActionResult UserAdd()
        {
            var userModel = _mapper.UserEditModelMapper.Map(new User());

            ViewBag.Title = Global.UserAdd_Title;

            return PartialView("UserEdit", userModel);
        }

        [HttpPost]
        [AjaxOnly]
        [ValidateAntiForgeryToken]
        public ActionResult UserAdd(UserAddModel userModel)
        {
            if (!ModelState.IsValid)
                return PartialView("ModalError", new ErrorModel {Message = Global.Error_UserValidation});

            var user = _mapper.UserMapper.Map(userModel);
            try
            {
                user = _unitOfWork.UserRepository.Insert(user);
                _unitOfWork.Commit();

                return Json(new
                {
                    id = user.UserId
                });
            }
            catch (RepositoryConcurrencyException)
            {
                return PartialView("ModalError", new ErrorModel { Message = Global.Error_UserConcurrency });
            }
            catch (RepositoryDuplicateException)
            {
                //TODO: Not user friendly
                return PartialView("ModalError", new ErrorModel { Message = Global.Error_UserValidation });
            }
        }

        [HttpPost]
        [AjaxOnly]
        public ActionResult UserDelete(int id)
        {
            _unitOfWork.UserRepository.DeleteByKey(id);
            _unitOfWork.Commit();

            return new EmptyResult();
        }

        [HttpGet]
        [AjaxOnly]
        public ActionResult UserRoles()
        {
            var usersList =
                Enum.GetValues(typeof (UserRoleModel.Role))
                    .Cast<UserRoleModel.Role>()
                    .Select(s => new
                    {
                        Text =
                            typeof (UserRoleModel.Role).GetField(s.ToString())
                                .GetCustomAttributes(typeof (DropDownNameAttribute), false)
                                .OfType<DropDownNameAttribute>()
                                .First()
                                .Name,
                        Value = s
                    });

            return Json(new
            {
                List = usersList
            }, JsonRequestBehavior.AllowGet);
        }

        [AjaxOnly]
        public ActionResult Responsibles(string orderBy = null, [JsonBinder] ResponsibleFilter filter = null)
        {
            var responsibleModels = _unitOfWork.ResponsibleRepository.GetAll(orderBy, filter)
                .Select(r => _mapper.ResponsibleViewModelMapper.Map(r))
                .ToList();

            return Json(new
            {
                totalItems = responsibleModels.Count,
                items = responsibleModels
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [AjaxOnly]
        public ActionResult ResponsibleEdit(int id)
        {
            var responsible = _unitOfWork.ResponsibleRepository.GetByKey(id);
            if (responsible == null)
                return PartialView("ModalError", new ErrorModel {Message = Global.Error_ResponsibleRemoved});

            var responsibleModel = _mapper.ResponsibleEditModelMapper.Map(responsible);

            ViewBag.Title = Global.ResponsibleEdit_Title;

            return PartialView(responsibleModel);
        }

        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ResponsibleEdit(ResponsibleEditModel responsibleModel)
        {
            if (!ModelState.IsValid)
                return PartialView("ModalError", new ErrorModel {Message = Global.Error_ResponsibleValidation});
            if (!_unitOfWork.ResponsibleRepository.Exists(responsibleModel.ResponsibleId))
                return PartialView("ModalError", new ErrorModel {Message = Global.Error_ResponsibleRemoved});

            var responsible = _mapper.ResponsibleMapper.Map(responsibleModel);
            try
            {
                _unitOfWork.ResponsibleRepository.Update(responsible);
                _unitOfWork.Commit();

                return Json(new
                {
                    id = responsible.ResponsibleId
                });
            }
            catch (RepositoryConcurrencyException)
            {
                return PartialView("ModalError", new ErrorModel {Message = Global.Error_ResponsibleConcurrency});
            }
            catch (RepositoryDuplicateException)
            {
                //TODO: Not user friendly
                return PartialView("ModalError", new ErrorModel { Message = Global.Error_ResponsibleValidation });
            }
        }

        [HttpGet]
        [AjaxOnly]
        public ActionResult ResponsibleAdd()
        {
            var responsibleModel = new ResponsibleEditModel
            {
                UsersList = _unitOfWork.UserRepository.GetAll()
                    .Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.UserId.ToString()
                    })
            };

            ViewBag.Title = Global.ResponsibleAdd_Title;

            return PartialView("ResponsibleEdit", responsibleModel);
        }

        [HttpPost]
        [AjaxOnly]
        [ValidateAntiForgeryToken]
        public ActionResult ResponsibleAdd(ResponsibleEditModel responsibleModel)
        {
            if (!ModelState.IsValid)
                return PartialView("ModalError", new ErrorModel {Message = Global.Error_ResponsibleValidation});

            var responsible = _mapper.ResponsibleMapper.Map(responsibleModel);
            try
            {
                responsible = _unitOfWork.ResponsibleRepository.Insert(responsible);
                _unitOfWork.Commit();

                return Json(new
                {
                    id = responsible.ResponsibleId
                });
            }
            catch (RepositoryConcurrencyException)
            {
                return PartialView("ModalError", new ErrorModel { Message = Global.Error_ResponsibleConcurrency });
            }
            catch (RepositoryDuplicateException)
            {
                //TODO: Not user friendly
                return PartialView("ModalError", new ErrorModel { Message = Global.Error_ResponsibleValidation });
            }
        }

        [AjaxOnly]
        [HttpPost]
        public ActionResult ResponsibleDelete(int id)
        {

CommissionsApplication.WebUI/Views/Users/Index.cshtml
@using CommissionsApplication.WebUI.App_GlobalResources
@{
  Layout = "~/Views/Shared/_AdminLayout.cshtml";
  ViewBag.Title = @Global.UsersView_Title;
}

@section scripts
{
  <script>
    require(["UsersView", "ResponsiblesView", "locales"], function(UsersView, ResponsiblesView, locales) {
      locales.load("@Url.Action("Locales", "Global")").done(function(locales) {
        var usersView = new UsersView(locales),
          responsiblesView = new ResponsiblesView(locales);

        usersView.render();
        responsiblesView.render();
      });
    });
  </script>
}

@Html.Hidden("users-url", Url.Action("Users"))
@Html.Hidden("user-add-url", Url.Action("UserAdd"))
@Html.Hidden("user-edit-url", Url.Action("UserEdit"))
@Html.Hidden("user-delete-url", Url.Action("UserDelete"))
@Html.Hidden("user-roles-url", Url.Action("UserRoles"))
@Html.Hidden("responsibles-url", Url.Action("Responsibles"))
@Html.Hidden("responsible-add-url", Url.Action("ResponsibleAdd"))
@Html.Hidden("responsible-edit-url", Url.Action("ResponsibleEdit"))
@Html.Hidden("responsible-delete-url", Url.Action("ResponsibleDelete"))

<div class="row-fluid">
  <div class="span8">
    <div id="users-grid"></div>
  </div>
  <div class="span4">
    <div id="responsibles-grid"></div>
  </div>
</div>

CommissionsApplication.WebUI/Views/Users/ResponsibleEdit.cshtml
@model CommissionsApplication.WebUI.Models.Concrete.ResponsibleEditModel

<div class="modal-header">
  <h4>@ViewBag.Title</h4>
</div>
<form>
  @Html.AntiForgeryToken()

  @Html.HiddenFor(x => x.ResponsibleId)
  @Html.HiddenFor(x => x.RowVersion)

  <div class="modal-body">
    <div class="row-fluid">
      <div class="span4">
        @Html.LabelFor(x => x.Name)
      </div>
      <div class="span8">
        @Html.TextBoxFor(x => x.Name, new {@class = "input-block-level"})
        @Html.ValidationMessageFor(x => x.Name, null, new {@class = "label label-important"})
      </div>
    </div>
    <div class="row-fluid">
      <div class="span4">
        @Html.LabelFor(x => x.Email)
      </div>
      <div class="span8">
        @Html.TextBoxFor(x => x.Email, new {@class = "input-block-level"})
        @Html.ValidationMessageFor(x => x.Email, null, new {@class = "label label-important"})
      </div>
    </div>
    <div class="row-fluid">
      <div class="span4">
        @Html.LabelFor(x => x.SelectedUserIds)
      </div>
      <div class="span8">
        @Html.ListBoxFor(x => x.SelectedUserIds, Model.UsersList, new {@class = "input-block-level multiselect"})
        @Html.ValidationMessageFor(x => x.SelectedUserIds, null, new {@class = "label label-important"})
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Закрыть</button>
    <button class="btn btn-primary" type="submit">Сохранить</button>
  </div>
</form>

CommissionsApplication.WebUI/Views/Users/UserEdit.cshtml
@using CommissionsApplication.WebUI.Helpers
@using CommissionsApplication.WebUI.Models.Concrete
@model CommissionsApplication.WebUI.Models.Abstract.IUserModel

<div class="modal-header">
  <h4>@ViewBag.Title</h4>
</div>
<form>
  @Html.AntiForgeryToken()

  @Html.HiddenFor(x => x.UserId)
  @Html.HiddenFor(x => x.RowVersion)

  <div class="modal-body">
    <div class="row-fluid">
      <div class="span4">
        @Html.LabelFor(x => x.Name)
      </div>
      <div class="span8">
        @Html.TextBoxFor(x => x.Name, new {@class = "input-block-level"})
        @Html.ValidationMessageFor(x => x.Name, null, new {@class = "label label-important"})
      </div>
    </div>
    <div class="row-fluid">
      <div class="span4">
        @Html.LabelFor(x => x.Login)
      </div>
      <div class="span8">
        @Html.TextBoxFor(x => x.Login, new {@class = "input-block-level"})
        @Html.ValidationMessageFor(x => x.Login, null, new {@class = "label label-important"})
      </div>
    </div>
    <div class="row-fluid">
      <div class="span4">
        @Html.LabelFor(x => x.Password)
      </div>
      <div class="span8">
        @if (Model is UserAddModel)
        {
          @Html.PasswordFor(x => (x as UserAddModel).Password, new {@class = "input-block-level"})
          @Html.ValidationMessageFor(x => (x as UserAddModel).Password, null, new {@class = "label label-important"})
        }
        else
        {
          @Html.PasswordFor(x => x.Password, new {@class = "input-block-level"})
          @Html.ValidationMessageFor(x => x.Password, null, new {@class = "label label-important"})
        }
      </div>
    </div>
    <div class="row-fluid">
      <div class="span4">
        @Html.LabelFor(x => x.RepeatPassword)
      </div>
      <div class="span8">
        @Html.PasswordFor(x => x.RepeatPassword, new {@class = "input-block-level"})
        @Html.ValidationMessageFor(x => x.RepeatPassword, null, new {@class = "label label-important"})
      </div>
    </div>
    <div class="row-fluid">
      <div class="span4">
        @Html.LabelFor(x => x.Email)
      </div>
      <div class="span8">
        @Html.TextBoxFor(x => x.Email, new {@class = "input-block-level"})
        @Html.ValidationMessageFor(x => x.Email, null, new {@class = "label label-important"})
      </div>
    </div>
    <div class="row-fluid">
      <div class="span4">
        @Html.LabelFor(x => x.UserRole)
      </div>
      <div class="span8">
        @Html.EnumDropDownListFor(x => x.UserRole, new {@class = "input-block-level"})
        @Html.ValidationMessageFor(x => x.UserRole, null, new {@class = "label label-important"})
      </div>
    </div>
    <div class="row-fluid">
      <div class="span4">
        @Html.LabelFor(x => x.SelectedResponsibleIds)
      </div>
      <div class="span8">
        @Html.ListBoxFor(x => x.SelectedResponsibleIds, Model.ResponsiblesList, new {@class = "input-block-level multiselect"})
        @Html.ValidationMessageFor(x => x.SelectedResponsibleIds, null, new {@class = "label label-important"})
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Закрыть</button>
    <button class="btn btn-primary" type="submit">Сохранить</button>
  </div>
</form>